"""empty message

Revision ID: 1368145668e4
Revises: be6c31d8feed
Create Date: 2025-08-07 08:44:33.342208

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1368145668e4'
down_revision = 'be6c31d8feed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.alter_column('homeworld_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('vehicle', schema=None) as batch_op:
        batch_op.alter_column('manufacturing_planet_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('character_owner_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicle', schema=None) as batch_op:
        batch_op.alter_column('character_owner_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('manufacturing_planet_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.alter_column('homeworld_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
