"""empty message

Revision ID: 154b991241d3
Revises: cc8b5a4ab94a
Create Date: 2025-07-31 18:05:40.547206

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '154b991241d3'
down_revision = 'cc8b5a4ab94a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicle', schema=None) as batch_op:
        batch_op.add_column(sa.Column('manufacturing_planet_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('vehicle_manufactoring_planet_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'planet', ['manufacturing_planet_id'], ['id'])
        batch_op.drop_column('manufactoring_planet_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicle', schema=None) as batch_op:
        batch_op.add_column(sa.Column('manufactoring_planet_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('vehicle_manufactoring_planet_id_fkey', 'planet', ['manufactoring_planet_id'], ['id'])
        batch_op.drop_column('manufacturing_planet_id')

    # ### end Alembic commands ###
